### ISSUE TITLE
Popup 字符集问题

### ISSUE THREAD

**Issue by spacelan** [stonexer/JD_Pai#1]

**Comment by stonexer** [comment]
你说啥！

**Comment by spacelan** [comment]
![default](https://cloud.githubusercontent.com/assets/3382212/8422583/0ff5e7f2-1f10-11e5-8fb8-10cbc2ff5cdc.jpg)

**Comment by stonexer** [comment]
what the fuck..这是什么鬼...我去改下字符集。。。

**Comment by stonexer** [comment]
大哥。。。你看看可以了不。。。为啥我这儿没出现过

**Comment by spacelan** [comment]
utf8可以了。。。

**Comment by spacelan** [comment]
不过为毛每次打开都特别慢

**Comment by stonexer** [comment]
我也发现了。。暂时木有发现原因。。不过这个没啥人点进去看吧。。
